#define KEYWORD 10
#define IDENTIFIER 11
#define INTEGER_CONSTANT 12
#define FLOATING_CONSTANT 13
#define CHARACTER_CONSTANT 14
#define STRING_LITERAL 15
#define PUNCTUATOR 16
#define SINGLE_LINE_COMMENT
// // #define SINGLE_LINE_COMMENT_END 18
#define MULTI_LINE_COMMENT
// // #define MULTI_LINE_COMMENT_END 20
#define INVALID_TOKEN -1